"""v4_initial_codes

Revision ID: 15826d464da8
Revises: 
Create Date: 2026-07-23 21:10:43.577432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15826d464da8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_sessions',
    sa.Column('session_code', sa.String(length=30), nullable=False),
    sa.Column('session_name', sa.String(length=20), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.CheckConstraint('end_year > start_year', name='ck_session_year'),
    sa.PrimaryKeyConstraint('session_code'),
    sa.UniqueConstraint('session_name'),
    sa.UniqueConstraint('session_name', name='uq_session_name')
    )
    op.create_index('idx_session_active', 'academic_sessions', ['is_current'], unique=False)
    op.create_index('idx_session_name', 'academic_sessions', ['session_name'], unique=False)
    op.create_index(op.f('ix_academic_sessions_is_active'), 'academic_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_academic_sessions_is_current'), 'academic_sessions', ['is_current'], unique=False)
    op.create_table('attachments',
    sa.Column('attachment_code', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=30), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('attachment_code')
    )
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_entity_type'), 'attachments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_attachments_is_active'), 'attachments', ['is_active'], unique=False)
    op.create_table('ka_course',
    sa.Column('ka_course_code', sa.String(length=30), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=True),
    sa.Column('course_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ka_course_code'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('ka_student',
    sa.Column('ka_student_code', sa.String(length=30), nullable=False),
    sa.Column('student_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('ka_student_code')
    )
    op.create_table('student_report',
    sa.Column('report_code', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('report_code')
    )
    op.create_table('time_slots',
    sa.Column('slot_code', sa.String(length=10), nullable=False),
    sa.Column('slot_name', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_slot_duration'),
    sa.PrimaryKeyConstraint('slot_code'),
    sa.UniqueConstraint('start_time', 'end_time', name='uq_slot_time')
    )
    op.create_index('idx_slot_code', 'time_slots', ['slot_code'], unique=False)
    op.create_index('idx_slot_order', 'time_slots', ['display_order'], unique=False)
    op.create_index(op.f('ix_time_slots_is_active'), 'time_slots', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('user_code', sa.String(length=30), nullable=False),
    sa.Column('admin_id', sa.String(length=30), nullable=True),
    sa.Column('teacher_id', sa.String(length=30), nullable=True),
    sa.Column('student_id', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('device_token', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_otp', sa.String(length=6), nullable=True),
    sa.Column('email_otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('last_password_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=30), nullable=True),
    sa.CheckConstraint("role IN ('ADMIN', 'TEACHER', 'STUDENT')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('user_code')
    )
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_phone_active', 'users', ['phone', 'is_active'], unique=False)
    op.create_index('idx_user_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_admin_id'), 'users', ['admin_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
    op.create_index(op.f('ix_users_teacher_id'), 'users', ['teacher_id'], unique=True)
    op.create_table('week_days',
    sa.Column('day_code', sa.String(length=3), nullable=False),
    sa.Column('day_name', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('display_order >= 1 AND display_order <= 7', name='ck_weekday_display_order'),
    sa.PrimaryKeyConstraint('day_code'),
    sa.UniqueConstraint('day_name')
    )
    op.create_index('idx_weekday_code', 'week_days', ['day_code'], unique=False)
    op.create_index('idx_weekday_name', 'week_days', ['day_name'], unique=False)
    op.create_index('idx_weekday_order', 'week_days', ['display_order'], unique=False)
    op.create_index(op.f('ix_week_days_is_active'), 'week_days', ['is_active'], unique=False)
    op.create_table('zoom_file',
    sa.Column('zoom_file_code', sa.String(length=30), nullable=False),
    sa.Column('file_initial', sa.String(length=255), nullable=False),
    sa.Column('transcript_file', sa.String(length=500), nullable=True),
    sa.Column('audio_file', sa.String(length=500), nullable=True),
    sa.Column('audio_duration', sa.String(length=30), nullable=True),
    sa.Column('video_file', sa.String(length=500), nullable=True),
    sa.Column('video_duration', sa.String(length=30), nullable=True),
    sa.Column('raw_date', sa.String(length=30), nullable=False),
    sa.Column('raw_time', sa.String(length=30), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('time', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('zoom_file_code'),
    sa.UniqueConstraint('file_initial', name='uq_zoom_file_initial')
    )
    op.create_index('idx_zoom_file_date', 'zoom_file', ['date'], unique=False)
    op.create_index(op.f('ix_zoom_file_date'), 'zoom_file', ['date'], unique=False)
    op.create_index(op.f('ix_zoom_file_file_initial'), 'zoom_file', ['file_initial'], unique=True)
    op.create_table('zoom_meeting',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('host_id', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('recording_count', sa.Integer(), nullable=True),
    sa.Column('share_url', sa.String(length=500), nullable=True),
    sa.Column('recording_play_passcode', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_zoom_meeting_host', 'zoom_meeting', ['host_id'], unique=False)
    op.create_index('idx_zoom_meeting_meeting_id', 'zoom_meeting', ['meeting_id'], unique=False)
    op.create_index('idx_zoom_meeting_start_time', 'zoom_meeting', ['start_time'], unique=False)
    op.create_index(op.f('ix_zoom_meeting_host_id'), 'zoom_meeting', ['host_id'], unique=False)
    op.create_index(op.f('ix_zoom_meeting_meeting_id'), 'zoom_meeting', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_zoom_meeting_start_time'), 'zoom_meeting', ['start_time'], unique=False)
    op.create_table('admin_profiles',
    sa.Column('admin_id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('admin_name', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_photo', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('can_create_admin', sa.Boolean(), nullable=False),
    sa.Column('super_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index('idx_admin_id', 'admin_profiles', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_profiles_admin_id'), 'admin_profiles', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_profiles_is_active'), 'admin_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_admin_profiles_user_id'), 'admin_profiles', ['user_id'], unique=True)
    op.create_table('ka_topic',
    sa.Column('topic_code', sa.String(length=30), nullable=False),
    sa.Column('course_id', sa.String(length=30), nullable=True),
    sa.Column('topic_id', sa.String(length=200), nullable=True),
    sa.Column('topic_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['ka_course.ka_course_code'], ),
    sa.PrimaryKeyConstraint('topic_code'),
    sa.UniqueConstraint('topic_id', name='uq_ka_topic_topic_id')
    )
    op.create_index('idx_ka_topic_course', 'ka_topic', ['course_id'], unique=False)
    op.create_index('idx_ka_topic_name', 'ka_topic', ['topic_name'], unique=False)
    op.create_index(op.f('ix_ka_topic_course_id'), 'ka_topic', ['course_id'], unique=False)
    op.create_index(op.f('ix_ka_topic_topic_id'), 'ka_topic', ['topic_id'], unique=True)
    op.create_index(op.f('ix_ka_topic_topic_name'), 'ka_topic', ['topic_name'], unique=False)
    op.create_table('student_profiles',
    sa.Column('student_id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('admission_number', sa.String(length=30), nullable=True),
    sa.Column('registration_number', sa.String(length=30), nullable=True),
    sa.Column('student_name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('school_address', sa.Text(), nullable=True),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('board', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('parent_name', sa.String(length=120), nullable=True),
    sa.Column('parent_phone', sa.String(length=10), nullable=True),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('guardian_phone', sa.String(length=10), nullable=True),
    sa.Column('emergency_contact', sa.String(length=10), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.student_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index('idx_student_id', 'student_profiles', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_admission_number'), 'student_profiles', ['admission_number'], unique=True)
    op.create_index(op.f('ix_student_profiles_is_active'), 'student_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_student_profiles_registration_number'), 'student_profiles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('subjects',
    sa.Column('subject_code', sa.String(length=30), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('subject_code'),
    sa.UniqueConstraint('subject_code', name='uq_subject_code'),
    sa.UniqueConstraint('subject_name', name='uq_subject_name')
    )
    op.create_index('idx_subject_active', 'subjects', ['is_active'], unique=False)
    op.create_index('idx_subject_name', 'subjects', ['subject_name'], unique=False)
    op.create_index(op.f('ix_subjects_is_active'), 'subjects', ['is_active'], unique=False)
    op.create_index(op.f('ix_subjects_subject_name'), 'subjects', ['subject_name'], unique=False)
    op.create_table('teacher_profiles',
    sa.Column('teacher_id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('teacher_name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('employee_code', sa.String(length=30), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('emergency_contact', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.teacher_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_index('idx_teacher_department', 'teacher_profiles', ['department'], unique=False)
    op.create_index('idx_teacher_employee', 'teacher_profiles', ['employee_code'], unique=False)
    op.create_index(op.f('ix_teacher_profiles_employee_code'), 'teacher_profiles', ['employee_code'], unique=True)
    op.create_index(op.f('ix_teacher_profiles_is_active'), 'teacher_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_teacher_profiles_user_id'), 'teacher_profiles', ['user_id'], unique=True)
    op.create_table('zoom_duration_report',
    sa.Column('duration_report_code', sa.String(length=30), nullable=False),
    sa.Column('report_id', sa.String(length=30), nullable=False),
    sa.Column('mean_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('min_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['student_report.report_code'], ),
    sa.PrimaryKeyConstraint('duration_report_code')
    )
    op.create_index('idx_zoom_duration_report', 'zoom_duration_report', ['report_id'], unique=False)
    op.create_index(op.f('ix_zoom_duration_report_report_id'), 'zoom_duration_report', ['report_id'], unique=False)
    op.create_table('zoom_interaction_report',
    sa.Column('interaction_report_code', sa.String(length=30), nullable=False),
    sa.Column('report_id', sa.String(length=30), nullable=False),
    sa.Column('mean_interaction_count', sa.Integer(), nullable=True),
    sa.Column('min_interaction_count', sa.Integer(), nullable=True),
    sa.Column('max_interaction_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['student_report.report_code'], ),
    sa.PrimaryKeyConstraint('interaction_report_code')
    )
    op.create_index('idx_zoom_interaction_report', 'zoom_interaction_report', ['report_id'], unique=False)
    op.create_index(op.f('ix_zoom_interaction_report_report_id'), 'zoom_interaction_report', ['report_id'], unique=False)
    op.create_table('zoom_recording_file',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('meeting_uuid', sa.String(length=64), nullable=False),
    sa.Column('recording_start', sa.DateTime(), nullable=True),
    sa.Column('recording_end', sa.DateTime(), nullable=True),
    sa.Column('file_type', sa.String(length=30), nullable=True),
    sa.Column('file_extension', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('play_url', sa.String(length=500), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('recording_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['meeting_uuid'], ['zoom_meeting.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_zoom_recording_meeting', 'zoom_recording_file', ['meeting_uuid'], unique=False)
    op.create_index('idx_zoom_recording_status', 'zoom_recording_file', ['status'], unique=False)
    op.create_index(op.f('ix_zoom_recording_file_meeting_uuid'), 'zoom_recording_file', ['meeting_uuid'], unique=False)
    op.create_index(op.f('ix_zoom_recording_file_status'), 'zoom_recording_file', ['status'], unique=False)
    op.create_table('classroom',
    sa.Column('class_code', sa.String(length=30), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('class_teacher_id', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['teacher_profiles.teacher_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('class_code'),
    sa.UniqueConstraint('academic_sessions_id', 'class_code', name='uq_classroom_session_classcode'),
    sa.UniqueConstraint('academic_sessions_id', 'class_name', 'section'),
    sa.UniqueConstraint('academic_sessions_id', 'display_name', name='uq_classroom_session_display')
    )
    op.create_index('idx_classroom_active', 'classroom', ['is_active'], unique=False)
    op.create_index('idx_classroom_code', 'classroom', ['class_code'], unique=False)
    op.create_index('idx_classroom_name', 'classroom', ['class_name'], unique=False)
    op.create_index('idx_classroom_section', 'classroom', ['section'], unique=False)
    op.create_index('idx_classroom_session', 'classroom', ['academic_sessions_id'], unique=False)
    op.create_index('idx_classroom_teacher', 'classroom', ['class_teacher_id'], unique=False)
    op.create_index(op.f('ix_classroom_academic_sessions_id'), 'classroom', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_classroom_class_teacher_id'), 'classroom', ['class_teacher_id'], unique=False)
    op.create_index(op.f('ix_classroom_is_active'), 'classroom', ['is_active'], unique=False)
    op.create_table('ka_topic_progress',
    sa.Column('topic_progress_code', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=True),
    sa.Column('course_id', sa.String(length=30), nullable=True),
    sa.Column('topic_id', sa.String(length=30), nullable=True),
    sa.Column('point_available', sa.Integer(), nullable=True),
    sa.Column('point_earned', sa.Integer(), nullable=True),
    sa.Column('percentage_earned', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['ka_course.ka_course_code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['ka_student.ka_student_code'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['ka_topic.topic_code'], ),
    sa.PrimaryKeyConstraint('topic_progress_code'),
    sa.UniqueConstraint('student_id', 'topic_id', 'date', name='_topic_progress_uc')
    )
    op.create_index('idx_topic_progress_date', 'ka_topic_progress', ['date'], unique=False)
    op.create_index('idx_topic_progress_student', 'ka_topic_progress', ['student_id'], unique=False)
    op.create_index('idx_topic_progress_topic', 'ka_topic_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_ka_topic_progress_course_id'), 'ka_topic_progress', ['course_id'], unique=False)
    op.create_index(op.f('ix_ka_topic_progress_date'), 'ka_topic_progress', ['date'], unique=False)
    op.create_index(op.f('ix_ka_topic_progress_student_id'), 'ka_topic_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_ka_topic_progress_topic_id'), 'ka_topic_progress', ['topic_id'], unique=False)
    op.create_table('student_id_cards',
    sa.Column('id_card_code', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('student_name', sa.String(length=120), nullable=False),
    sa.Column('parent_name', sa.String(length=120), nullable=True),
    sa.Column('class_display_name', sa.String(length=150), nullable=True),
    sa.Column('institute_name', sa.String(length=255), nullable=False),
    sa.Column('institute_contact_number', sa.String(length=30), nullable=False),
    sa.Column('academic_session_label', sa.String(length=120), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('valid_till', sa.Date(), nullable=True),
    sa.Column('institute_logo_path', sa.String(length=500), nullable=True),
    sa.Column('student_photo_path', sa.String(length=500), nullable=True),
    sa.Column('qr_code_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('student_id_business', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_card_code'),
    sa.UniqueConstraint('student_id', 'academic_sessions_id', name='uq_student_idcard_student_session')
    )
    op.create_index('idx_student_id_cards_session', 'student_id_cards', ['academic_sessions_id'], unique=False)
    op.create_index('idx_student_id_cards_student', 'student_id_cards', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_id_cards_academic_sessions_id'), 'student_id_cards', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_student_id_cards_is_active'), 'student_id_cards', ['is_active'], unique=False)
    op.create_index(op.f('ix_student_id_cards_student_id'), 'student_id_cards', ['student_id'], unique=False)
    op.create_table('zoom_student_interaction',
    sa.Column('zoom_interaction_code', sa.String(length=30), nullable=False),
    sa.Column('zoom_file_id', sa.String(length=64), nullable=False),
    sa.Column('class_date', sa.DateTime(), nullable=True),
    sa.Column('class_name', sa.String(length=150), nullable=True),
    sa.Column('interaction_time', sa.String(length=30), nullable=False),
    sa.Column('interaction_duration', sa.Float(), nullable=False),
    sa.Column('speaker_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['zoom_file_id'], ['zoom_recording_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('zoom_interaction_code')
    )
    op.create_index('idx_zoom_interaction_class_date', 'zoom_student_interaction', ['class_date'], unique=False)
    op.create_index('idx_zoom_interaction_file', 'zoom_student_interaction', ['zoom_file_id'], unique=False)
    op.create_index('idx_zoom_interaction_speaker', 'zoom_student_interaction', ['speaker_name'], unique=False)
    op.create_index(op.f('ix_zoom_student_interaction_class_date'), 'zoom_student_interaction', ['class_date'], unique=False)
    op.create_index(op.f('ix_zoom_student_interaction_speaker_name'), 'zoom_student_interaction', ['speaker_name'], unique=False)
    op.create_index(op.f('ix_zoom_student_interaction_zoom_file_id'), 'zoom_student_interaction', ['zoom_file_id'], unique=False)
    op.create_table('zoom_transcript',
    sa.Column('zoom_transcript_code', sa.String(length=30), nullable=False),
    sa.Column('zoom_file_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=30), nullable=False),
    sa.Column('end_time', sa.String(length=30), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('speaker', sa.String(length=150), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('class_name', sa.String(length=150), nullable=True),
    sa.Column('class_date', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['zoom_file_id'], ['zoom_recording_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('zoom_transcript_code')
    )
    op.create_index('idx_zoom_transcript_class_date', 'zoom_transcript', ['class_date'], unique=False)
    op.create_index('idx_zoom_transcript_file', 'zoom_transcript', ['zoom_file_id'], unique=False)
    op.create_index('idx_zoom_transcript_speaker', 'zoom_transcript', ['speaker'], unique=False)
    op.create_index(op.f('ix_zoom_transcript_class_date'), 'zoom_transcript', ['class_date'], unique=False)
    op.create_index(op.f('ix_zoom_transcript_speaker'), 'zoom_transcript', ['speaker'], unique=False)
    op.create_index(op.f('ix_zoom_transcript_zoom_file_id'), 'zoom_transcript', ['zoom_file_id'], unique=False)
    op.create_table('class_subjects',
    sa.Column('class_subject_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('classroom_id', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.class_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('class_subject_code'),
    sa.UniqueConstraint('academic_sessions_id', 'classroom_id', 'subject_id', name='uq_class_subject')
    )
    op.create_index('idx_class_subject_active', 'class_subjects', ['is_active'], unique=False)
    op.create_index('idx_class_subject_class', 'class_subjects', ['classroom_id'], unique=False)
    op.create_index('idx_class_subject_session', 'class_subjects', ['academic_sessions_id'], unique=False)
    op.create_index('idx_class_subject_subject', 'class_subjects', ['subject_id'], unique=False)
    op.create_index(op.f('ix_class_subjects_academic_sessions_id'), 'class_subjects', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_class_subjects_classroom_id'), 'class_subjects', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_class_subjects_is_active'), 'class_subjects', ['is_active'], unique=False)
    op.create_index(op.f('ix_class_subjects_subject_id'), 'class_subjects', ['subject_id'], unique=False)
    op.create_table('notices',
    sa.Column('notice_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('classroom_id', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('notice_type', sa.Enum('GENERAL', 'ACADEMIC', 'EXAM', 'FEE', 'EVENT', name='noticetype'), nullable=False),
    sa.Column('audience', sa.Enum('ALL', 'CLASS', 'SECTION', 'TEACHER', 'STUDENT', name='noticeaudience'), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('deleted_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(expiry_date IS NULL) OR (expiry_date >= publish_date)', name='ck_notice_expiry'),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.class_code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('notice_code')
    )
    op.create_index('idx_notice_class', 'notices', ['classroom_id', 'publish_date'], unique=False)
    op.create_index('idx_notice_pin', 'notices', ['is_pinned', 'publish_date'], unique=False)
    op.create_index('idx_notice_publish', 'notices', ['publish_date', 'audience'], unique=False)
    op.create_index(op.f('ix_notices_academic_sessions_id'), 'notices', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_notices_audience'), 'notices', ['audience'], unique=False)
    op.create_index(op.f('ix_notices_classroom_id'), 'notices', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_notices_expiry_date'), 'notices', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_notices_is_active'), 'notices', ['is_active'], unique=False)
    op.create_index(op.f('ix_notices_is_pinned'), 'notices', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_notices_notice_type'), 'notices', ['notice_type'], unique=False)
    op.create_index(op.f('ix_notices_publish_date'), 'notices', ['publish_date'], unique=False)
    op.create_table('student_classes',
    sa.Column('student_class_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=False),
    sa.Column('classroom_id', sa.String(length=30), nullable=False),
    sa.Column('roll_number', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('roll_number_locked', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.class_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_class_code'),
    sa.UniqueConstraint('academic_sessions_id', 'classroom_id', 'roll_number', name='uq_roll_class'),
    sa.UniqueConstraint('academic_sessions_id', 'student_id', name='uq_student_session')
    )
    op.create_index('idx_studentclass_class', 'student_classes', ['classroom_id'], unique=False)
    op.create_index('idx_studentclass_roll', 'student_classes', ['roll_number'], unique=False)
    op.create_index('idx_studentclass_session', 'student_classes', ['academic_sessions_id'], unique=False)
    op.create_index('idx_studentclass_status', 'student_classes', ['status'], unique=False)
    op.create_index('idx_studentclass_student', 'student_classes', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_classes_academic_sessions_id'), 'student_classes', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_student_classes_classroom_id'), 'student_classes', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_student_classes_is_active'), 'student_classes', ['is_active'], unique=False)
    op.create_index(op.f('ix_student_classes_roll_number'), 'student_classes', ['roll_number'], unique=False)
    op.create_index(op.f('ix_student_classes_status'), 'student_classes', ['status'], unique=False)
    op.create_index(op.f('ix_student_classes_student_id'), 'student_classes', ['student_id'], unique=False)
    op.create_table('student_promotion_history',
    sa.Column('promotion_code', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=False),
    sa.Column('from_session_id', sa.String(length=30), nullable=False),
    sa.Column('to_session_id', sa.String(length=30), nullable=False),
    sa.Column('from_classroom_id', sa.String(length=30), nullable=False),
    sa.Column('to_classroom_id', sa.String(length=30), nullable=False),
    sa.Column('previous_roll_number', sa.Integer(), nullable=False),
    sa.Column('new_roll_number', sa.Integer(), nullable=False),
    sa.Column('promotion_date', sa.Date(), nullable=False),
    sa.Column('promotion_type', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('promoted_by_user_id', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_classroom_id'], ['classroom.class_code'], ),
    sa.ForeignKeyConstraint(['from_session_id'], ['academic_sessions.session_code'], ),
    sa.ForeignKeyConstraint(['promoted_by_user_id'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_classroom_id'], ['classroom.class_code'], ),
    sa.ForeignKeyConstraint(['to_session_id'], ['academic_sessions.session_code'], ),
    sa.PrimaryKeyConstraint('promotion_code')
    )
    op.create_index('idx_student_promotion_date', 'student_promotion_history', ['promotion_date'], unique=False)
    op.create_index('idx_student_promotion_student', 'student_promotion_history', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_promotion_history_student_id'), 'student_promotion_history', ['student_id'], unique=False)
    op.create_table('student_topic_progress_report',
    sa.Column('topic_progress_report_code', sa.String(length=30), nullable=False),
    sa.Column('report_id', sa.String(length=30), nullable=False),
    sa.Column('topic_id', sa.String(length=30), nullable=False),
    sa.Column('topic_progress_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['student_report.report_code'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['ka_topic.topic_code'], ),
    sa.ForeignKeyConstraint(['topic_progress_id'], ['ka_topic_progress.topic_progress_code'], ),
    sa.PrimaryKeyConstraint('topic_progress_report_code')
    )
    op.create_index('idx_student_topic_report_progress', 'student_topic_progress_report', ['topic_progress_id'], unique=False)
    op.create_index('idx_student_topic_report_report', 'student_topic_progress_report', ['report_id'], unique=False)
    op.create_index('idx_student_topic_report_topic', 'student_topic_progress_report', ['topic_id'], unique=False)
    op.create_index(op.f('ix_student_topic_progress_report_report_id'), 'student_topic_progress_report', ['report_id'], unique=False)
    op.create_index(op.f('ix_student_topic_progress_report_topic_id'), 'student_topic_progress_report', ['topic_id'], unique=False)
    op.create_index(op.f('ix_student_topic_progress_report_topic_progress_id'), 'student_topic_progress_report', ['topic_progress_id'], unique=False)
    op.create_table('fees',
    sa.Column('fee_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('student_class_id', sa.String(length=30), nullable=False),
    sa.Column('fee_month', sa.Integer(), nullable=False),
    sa.Column('fee_year', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'CANCELLED', name='feestatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('deleted_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('discount_amount>=0', name='ck_discount_amount'),
    sa.CheckConstraint('fee_month >=1 AND fee_month<=12', name='ck_fee_month'),
    sa.CheckConstraint('fine_amount>=0', name='ck_fine_amount'),
    sa.CheckConstraint('paid_amount>=0', name='ck_paid_amount'),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['student_class_id'], ['student_classes.student_class_code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('fee_code'),
    sa.UniqueConstraint('student_class_id', 'fee_month', 'fee_year', name='uq_student_fee')
    )
    op.create_index('idx_fee_due', 'fees', ['due_date', 'status'], unique=False)
    op.create_index('idx_fee_student', 'fees', ['student_class_id', 'status'], unique=False)
    op.create_index(op.f('ix_fees_academic_sessions_id'), 'fees', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_fees_is_active'), 'fees', ['is_active'], unique=False)
    op.create_index(op.f('ix_fees_status'), 'fees', ['status'], unique=False)
    op.create_index(op.f('ix_fees_student_class_id'), 'fees', ['student_class_id'], unique=False)
    op.create_table('student_attendance',
    sa.Column('attendance_code', sa.String(length=30), nullable=False),
    sa.Column('student_class_id', sa.String(length=30), nullable=False),
    sa.Column('total_classes', sa.Integer(), nullable=True),
    sa.Column('present_classes', sa.Integer(), nullable=True),
    sa.Column('absent_classes', sa.Integer(), nullable=True),
    sa.Column('attendance_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_class_id'], ['student_classes.student_class_code'], ),
    sa.PrimaryKeyConstraint('attendance_code'),
    sa.UniqueConstraint('student_class_id')
    )
    op.create_index('idx_student_attendance', 'student_attendance', ['student_class_id'], unique=False)
    op.create_table('teacher_subjects',
    sa.Column('teacher_subject_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('class_subject_id', sa.String(length=30), nullable=False),
    sa.Column('classroom_id', sa.String(length=30), nullable=False),
    sa.Column('subject_id', sa.String(length=30), nullable=False),
    sa.Column('teacher_id', sa.String(length=30), nullable=False),
    sa.Column('is_class_teacher', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.class_subject_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.class_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_subject_code'),
    sa.UniqueConstraint('academic_sessions_id', 'classroom_id', 'subject_id', name='uq_teacher_subject')
    )
    op.create_index('idx_teacher_subject_class', 'teacher_subjects', ['classroom_id'], unique=False)
    op.create_index('idx_teacher_subject_subject', 'teacher_subjects', ['subject_id'], unique=False)
    op.create_index('idx_teacher_subject_teacher', 'teacher_subjects', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_academic_sessions_id'), 'teacher_subjects', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_class_subject_id'), 'teacher_subjects', ['class_subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_classroom_id'), 'teacher_subjects', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_is_active'), 'teacher_subjects', ['is_active'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_subject_id'), 'teacher_subjects', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_subjects_teacher_id'), 'teacher_subjects', ['teacher_id'], unique=False)
    op.create_table('assignments',
    sa.Column('assignment_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('classroom_id', sa.String(length=30), nullable=False),
    sa.Column('class_subject_id', sa.String(length=30), nullable=False),
    sa.Column('teacher_subject_id', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('passing_marks', sa.Float(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', 'DELETED', name='assignmentstatus'), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('close_at', sa.DateTime(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('checked_students', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('deleted_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.class_subject_code'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.class_code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['teacher_subject_id'], ['teacher_subjects.teacher_subject_code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('assignment_code'),
    sa.UniqueConstraint('class_subject_id', 'title', 'due_date', name='uq_assignment')
    )
    op.create_index('idx_assignment_class', 'assignments', ['classroom_id', 'due_date'], unique=False)
    op.create_index('idx_assignment_session', 'assignments', ['academic_sessions_id', 'status'], unique=False)
    op.create_index('idx_assignment_teacher', 'assignments', ['teacher_subject_id', 'status'], unique=False)
    op.create_index(op.f('ix_assignments_academic_sessions_id'), 'assignments', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_assignments_class_subject_id'), 'assignments', ['class_subject_id'], unique=False)
    op.create_index(op.f('ix_assignments_classroom_id'), 'assignments', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_assignments_due_date'), 'assignments', ['due_date'], unique=False)
    op.create_index(op.f('ix_assignments_is_active'), 'assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_teacher_subject_id'), 'assignments', ['teacher_subject_id'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('chat_room_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('student_class_id', sa.String(length=30), nullable=False),
    sa.Column('teacher_subject_id', sa.String(length=30), nullable=False),
    sa.Column('last_message', sa.String(length=500), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('student_unread', sa.Integer(), nullable=False),
    sa.Column('teacher_unread', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ),
    sa.ForeignKeyConstraint(['student_class_id'], ['student_classes.student_class_code'], ),
    sa.ForeignKeyConstraint(['teacher_subject_id'], ['teacher_subjects.teacher_subject_code'], ),
    sa.PrimaryKeyConstraint('chat_room_code'),
    sa.UniqueConstraint('student_class_id', 'teacher_subject_id', name='uq_chat_room')
    )
    op.create_index('idx_chat_room', 'chat_rooms', ['teacher_subject_id', 'student_class_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_academic_sessions_id'), 'chat_rooms', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_is_active'), 'chat_rooms', ['is_active'], unique=False)
    op.create_index(op.f('ix_chat_rooms_student_class_id'), 'chat_rooms', ['student_class_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_teacher_subject_id'), 'chat_rooms', ['teacher_subject_id'], unique=False)
    op.create_table('class_timetable',
    sa.Column('timetable_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('classroom_id', sa.String(length=30), nullable=False),
    sa.Column('class_subject_id', sa.String(length=30), nullable=False),
    sa.Column('teacher_subject_id', sa.String(length=30), nullable=False),
    sa.Column('week_day_id', sa.String(length=3), nullable=False),
    sa.Column('time_slot_id', sa.String(length=10), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.class_subject_code'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.class_code'], ),
    sa.ForeignKeyConstraint(['teacher_subject_id'], ['teacher_subjects.teacher_subject_code'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.slot_code'], ),
    sa.ForeignKeyConstraint(['week_day_id'], ['week_days.day_code'], ),
    sa.PrimaryKeyConstraint('timetable_code'),
    sa.UniqueConstraint('academic_sessions_id', 'classroom_id', 'week_day_id', 'time_slot_id', name='uq_class_slot'),
    sa.UniqueConstraint('academic_sessions_id', 'teacher_subject_id', 'week_day_id', 'time_slot_id', name='uq_teacher_slot')
    )
    op.create_index('idx_timetable_class', 'class_timetable', ['classroom_id'], unique=False)
    op.create_index('idx_timetable_day', 'class_timetable', ['week_day_id'], unique=False)
    op.create_index('idx_timetable_session', 'class_timetable', ['academic_sessions_id'], unique=False)
    op.create_index('idx_timetable_slot', 'class_timetable', ['time_slot_id'], unique=False)
    op.create_index('idx_timetable_teacher', 'class_timetable', ['teacher_subject_id'], unique=False)
    op.create_index(op.f('ix_class_timetable_is_active'), 'class_timetable', ['is_active'], unique=False)
    op.create_table('exams',
    sa.Column('exam_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('classroom_id', sa.String(length=30), nullable=False),
    sa.Column('class_subject_id', sa.String(length=30), nullable=False),
    sa.Column('teacher_subject_id', sa.String(length=30), nullable=False),
    sa.Column('exam_name', sa.String(length=150), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('passing_marks', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'COMPLETED', 'CANCELLED', name='examstatus'), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('result_uploaded', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('deleted_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.class_subject_code'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.class_code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['teacher_subject_id'], ['teacher_subjects.teacher_subject_code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('exam_code'),
    sa.UniqueConstraint('class_subject_id', 'exam_name', 'exam_date', name='uq_exam')
    )
    op.create_index('idx_exam_class', 'exams', ['classroom_id', 'exam_date'], unique=False)
    op.create_index('idx_exam_teacher', 'exams', ['teacher_subject_id', 'status'], unique=False)
    op.create_index(op.f('ix_exams_academic_sessions_id'), 'exams', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_exams_class_subject_id'), 'exams', ['class_subject_id'], unique=False)
    op.create_index(op.f('ix_exams_classroom_id'), 'exams', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_exams_exam_date'), 'exams', ['exam_date'], unique=False)
    op.create_index(op.f('ix_exams_is_active'), 'exams', ['is_active'], unique=False)
    op.create_index(op.f('ix_exams_status'), 'exams', ['status'], unique=False)
    op.create_index(op.f('ix_exams_teacher_subject_id'), 'exams', ['teacher_subject_id'], unique=False)
    op.create_table('study_materials',
    sa.Column('material_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('classroom_id', sa.String(length=30), nullable=False),
    sa.Column('class_subject_id', sa.String(length=30), nullable=False),
    sa.Column('teacher_subject_id', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('material_type', sa.Enum('PDF', 'VIDEO', 'DOCUMENT', 'LINK', 'OTHER', name='materialtype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.class_subject_code'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.class_code'], ),
    sa.ForeignKeyConstraint(['teacher_subject_id'], ['teacher_subjects.teacher_subject_code'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('material_code'),
    sa.UniqueConstraint('class_subject_id', 'title', name='uq_material_title')
    )
    op.create_index('idx_material_class', 'study_materials', ['classroom_id', 'class_subject_id'], unique=False)
    op.create_index('idx_material_teacher', 'study_materials', ['teacher_subject_id'], unique=False)
    op.create_index(op.f('ix_study_materials_academic_sessions_id'), 'study_materials', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_study_materials_class_subject_id'), 'study_materials', ['class_subject_id'], unique=False)
    op.create_index(op.f('ix_study_materials_classroom_id'), 'study_materials', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_study_materials_is_active'), 'study_materials', ['is_active'], unique=False)
    op.create_index(op.f('ix_study_materials_teacher_subject_id'), 'study_materials', ['teacher_subject_id'], unique=False)
    op.create_table('teacher_availability',
    sa.Column('availability_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('teacher_subject_id', sa.String(length=30), nullable=False),
    sa.Column('week_day_id', sa.String(length=3), nullable=False),
    sa.Column('time_slot_id', sa.String(length=10), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ),
    sa.ForeignKeyConstraint(['teacher_subject_id'], ['teacher_subjects.teacher_subject_code'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.slot_code'], ),
    sa.ForeignKeyConstraint(['week_day_id'], ['week_days.day_code'], ),
    sa.PrimaryKeyConstraint('availability_code'),
    sa.UniqueConstraint('academic_sessions_id', 'teacher_subject_id', 'week_day_id', 'time_slot_id', name='uq_teacher_availability')
    )
    op.create_index('idx_teacher_availability_day', 'teacher_availability', ['week_day_id'], unique=False)
    op.create_index('idx_teacher_availability_session', 'teacher_availability', ['academic_sessions_id'], unique=False)
    op.create_index('idx_teacher_availability_slot', 'teacher_availability', ['time_slot_id'], unique=False)
    op.create_index('idx_teacher_availability_teacher', 'teacher_availability', ['teacher_subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_availability_is_active'), 'teacher_availability', ['is_active'], unique=False)
    op.create_table('assignment_results',
    sa.Column('assignment_result_code', sa.String(length=30), nullable=False),
    sa.Column('assignment_id', sa.String(length=30), nullable=False),
    sa.Column('student_class_id', sa.String(length=30), nullable=False),
    sa.Column('obtained_marks', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('checked_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_code'], ),
    sa.ForeignKeyConstraint(['checked_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['student_class_id'], ['student_classes.student_class_code'], ),
    sa.PrimaryKeyConstraint('assignment_result_code'),
    sa.UniqueConstraint('assignment_id', 'student_class_id', name='uq_assignment_result')
    )
    op.create_index('idx_assignment_result', 'assignment_results', ['student_class_id', 'is_checked'], unique=False)
    op.create_index(op.f('ix_assignment_results_assignment_id'), 'assignment_results', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_results_is_active'), 'assignment_results', ['is_active'], unique=False)
    op.create_index(op.f('ix_assignment_results_student_class_id'), 'assignment_results', ['student_class_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('chat_message_code', sa.String(length=30), nullable=False),
    sa.Column('chat_room_id', sa.String(length=30), nullable=False),
    sa.Column('sender_id', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.chat_room_code'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_code'], ),
    sa.PrimaryKeyConstraint('chat_message_code')
    )
    op.create_index('idx_chat_message', 'chat_messages', ['chat_room_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_chat_room_id'), 'chat_messages', ['chat_room_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_is_active'), 'chat_messages', ['is_active'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_table('daily_classes',
    sa.Column('daily_class_code', sa.String(length=30), nullable=False),
    sa.Column('academic_sessions_id', sa.String(length=30), nullable=False),
    sa.Column('classroom_id', sa.String(length=30), nullable=False),
    sa.Column('class_subject_id', sa.String(length=30), nullable=False),
    sa.Column('teacher_subject_id', sa.String(length=30), nullable=False),
    sa.Column('timetable_id', sa.String(length=30), nullable=True),
    sa.Column('class_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('homework', sa.Text(), nullable=True),
    sa.Column('lecture_status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('total_minutes', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_sessions_id'], ['academic_sessions.session_code'], ),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.class_subject_code'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.class_code'], ),
    sa.ForeignKeyConstraint(['teacher_subject_id'], ['teacher_subjects.teacher_subject_code'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['class_timetable.timetable_code'], ),
    sa.PrimaryKeyConstraint('daily_class_code'),
    sa.UniqueConstraint('teacher_subject_id', 'class_date', 'timetable_id', name='uq_daily_class')
    )
    op.create_index('idx_daily_classes_class_date', 'daily_classes', ['classroom_id', 'class_date'], unique=False)
    op.create_index('idx_daily_classes_teacher', 'daily_classes', ['teacher_subject_id', 'class_date'], unique=False)
    op.create_index(op.f('ix_daily_classes_academic_sessions_id'), 'daily_classes', ['academic_sessions_id'], unique=False)
    op.create_index(op.f('ix_daily_classes_class_date'), 'daily_classes', ['class_date'], unique=False)
    op.create_index(op.f('ix_daily_classes_class_subject_id'), 'daily_classes', ['class_subject_id'], unique=False)
    op.create_index(op.f('ix_daily_classes_classroom_id'), 'daily_classes', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_daily_classes_is_active'), 'daily_classes', ['is_active'], unique=False)
    op.create_index(op.f('ix_daily_classes_lecture_status'), 'daily_classes', ['lecture_status'], unique=False)
    op.create_index(op.f('ix_daily_classes_teacher_subject_id'), 'daily_classes', ['teacher_subject_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('exam_result_code', sa.String(length=30), nullable=False),
    sa.Column('exam_id', sa.String(length=30), nullable=False),
    sa.Column('student_class_id', sa.String(length=30), nullable=False),
    sa.Column('obtained_marks', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('rank_in_class', sa.Integer(), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=True),
    sa.Column('checked_by', sa.String(length=30), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['checked_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_code'], ),
    sa.ForeignKeyConstraint(['student_class_id'], ['student_classes.student_class_code'], ),
    sa.PrimaryKeyConstraint('exam_result_code'),
    sa.UniqueConstraint('exam_id', 'student_class_id', name='uq_exam_result')
    )
    op.create_index('idx_exam_rank', 'exam_results', ['exam_id', 'rank_in_class'], unique=False)
    op.create_index('idx_exam_result', 'exam_results', ['student_class_id', 'exam_id'], unique=False)
    op.create_index(op.f('ix_exam_results_exam_id'), 'exam_results', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_results_is_active'), 'exam_results', ['is_active'], unique=False)
    op.create_index(op.f('ix_exam_results_student_class_id'), 'exam_results', ['student_class_id'], unique=False)
    op.create_table('daily_class_students',
    sa.Column('daily_class_student_code', sa.String(length=30), nullable=False),
    sa.Column('daily_class_id', sa.String(length=30), nullable=False),
    sa.Column('student_class_id', sa.String(length=30), nullable=False),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('marked_by', sa.String(length=30), nullable=True),
    sa.Column('marked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_class_id'], ['daily_classes.daily_class_code'], ),
    sa.ForeignKeyConstraint(['marked_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['student_class_id'], ['student_classes.student_class_code'], ),
    sa.PrimaryKeyConstraint('daily_class_student_code'),
    sa.UniqueConstraint('daily_class_id', 'student_class_id', name='uq_daily_student')
    )
    op.create_index('idx_daily_student', 'daily_class_students', ['student_class_id', 'attendance_status'], unique=False)
    op.create_index(op.f('ix_daily_class_students_attendance_status'), 'daily_class_students', ['attendance_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_class_students_attendance_status'), table_name='daily_class_students')
    op.drop_index('idx_daily_student', table_name='daily_class_students')
    op.drop_table('daily_class_students')
    op.drop_index(op.f('ix_exam_results_student_class_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_is_active'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_exam_id'), table_name='exam_results')
    op.drop_index('idx_exam_result', table_name='exam_results')
    op.drop_index('idx_exam_rank', table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_daily_classes_teacher_subject_id'), table_name='daily_classes')
    op.drop_index(op.f('ix_daily_classes_lecture_status'), table_name='daily_classes')
    op.drop_index(op.f('ix_daily_classes_is_active'), table_name='daily_classes')
    op.drop_index(op.f('ix_daily_classes_classroom_id'), table_name='daily_classes')
    op.drop_index(op.f('ix_daily_classes_class_subject_id'), table_name='daily_classes')
    op.drop_index(op.f('ix_daily_classes_class_date'), table_name='daily_classes')
    op.drop_index(op.f('ix_daily_classes_academic_sessions_id'), table_name='daily_classes')
    op.drop_index('idx_daily_classes_teacher', table_name='daily_classes')
    op.drop_index('idx_daily_classes_class_date', table_name='daily_classes')
    op.drop_table('daily_classes')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_is_active'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_chat_room_id'), table_name='chat_messages')
    op.drop_index('idx_chat_message', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_assignment_results_student_class_id'), table_name='assignment_results')
    op.drop_index(op.f('ix_assignment_results_is_active'), table_name='assignment_results')
    op.drop_index(op.f('ix_assignment_results_assignment_id'), table_name='assignment_results')
    op.drop_index('idx_assignment_result', table_name='assignment_results')
    op.drop_table('assignment_results')
    op.drop_index(op.f('ix_teacher_availability_is_active'), table_name='teacher_availability')
    op.drop_index('idx_teacher_availability_teacher', table_name='teacher_availability')
    op.drop_index('idx_teacher_availability_slot', table_name='teacher_availability')
    op.drop_index('idx_teacher_availability_session', table_name='teacher_availability')
    op.drop_index('idx_teacher_availability_day', table_name='teacher_availability')
    op.drop_table('teacher_availability')
    op.drop_index(op.f('ix_study_materials_teacher_subject_id'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_is_active'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_classroom_id'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_class_subject_id'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_academic_sessions_id'), table_name='study_materials')
    op.drop_index('idx_material_teacher', table_name='study_materials')
    op.drop_index('idx_material_class', table_name='study_materials')
    op.drop_table('study_materials')
    op.drop_index(op.f('ix_exams_teacher_subject_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_status'), table_name='exams')
    op.drop_index(op.f('ix_exams_is_active'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_date'), table_name='exams')
    op.drop_index(op.f('ix_exams_classroom_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_class_subject_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_academic_sessions_id'), table_name='exams')
    op.drop_index('idx_exam_teacher', table_name='exams')
    op.drop_index('idx_exam_class', table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_class_timetable_is_active'), table_name='class_timetable')
    op.drop_index('idx_timetable_teacher', table_name='class_timetable')
    op.drop_index('idx_timetable_slot', table_name='class_timetable')
    op.drop_index('idx_timetable_session', table_name='class_timetable')
    op.drop_index('idx_timetable_day', table_name='class_timetable')
    op.drop_index('idx_timetable_class', table_name='class_timetable')
    op.drop_table('class_timetable')
    op.drop_index(op.f('ix_chat_rooms_teacher_subject_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_student_class_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_is_active'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_academic_sessions_id'), table_name='chat_rooms')
    op.drop_index('idx_chat_room', table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_assignments_teacher_subject_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_is_active'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_due_date'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_classroom_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_class_subject_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_academic_sessions_id'), table_name='assignments')
    op.drop_index('idx_assignment_teacher', table_name='assignments')
    op.drop_index('idx_assignment_session', table_name='assignments')
    op.drop_index('idx_assignment_class', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_teacher_subjects_teacher_id'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_subject_id'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_is_active'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_classroom_id'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_class_subject_id'), table_name='teacher_subjects')
    op.drop_index(op.f('ix_teacher_subjects_academic_sessions_id'), table_name='teacher_subjects')
    op.drop_index('idx_teacher_subject_teacher', table_name='teacher_subjects')
    op.drop_index('idx_teacher_subject_subject', table_name='teacher_subjects')
    op.drop_index('idx_teacher_subject_class', table_name='teacher_subjects')
    op.drop_table('teacher_subjects')
    op.drop_index('idx_student_attendance', table_name='student_attendance')
    op.drop_table('student_attendance')
    op.drop_index(op.f('ix_fees_student_class_id'), table_name='fees')
    op.drop_index(op.f('ix_fees_status'), table_name='fees')
    op.drop_index(op.f('ix_fees_is_active'), table_name='fees')
    op.drop_index(op.f('ix_fees_academic_sessions_id'), table_name='fees')
    op.drop_index('idx_fee_student', table_name='fees')
    op.drop_index('idx_fee_due', table_name='fees')
    op.drop_table('fees')
    op.drop_index(op.f('ix_student_topic_progress_report_topic_progress_id'), table_name='student_topic_progress_report')
    op.drop_index(op.f('ix_student_topic_progress_report_topic_id'), table_name='student_topic_progress_report')
    op.drop_index(op.f('ix_student_topic_progress_report_report_id'), table_name='student_topic_progress_report')
    op.drop_index('idx_student_topic_report_topic', table_name='student_topic_progress_report')
    op.drop_index('idx_student_topic_report_report', table_name='student_topic_progress_report')
    op.drop_index('idx_student_topic_report_progress', table_name='student_topic_progress_report')
    op.drop_table('student_topic_progress_report')
    op.drop_index(op.f('ix_student_promotion_history_student_id'), table_name='student_promotion_history')
    op.drop_index('idx_student_promotion_student', table_name='student_promotion_history')
    op.drop_index('idx_student_promotion_date', table_name='student_promotion_history')
    op.drop_table('student_promotion_history')
    op.drop_index(op.f('ix_student_classes_student_id'), table_name='student_classes')
    op.drop_index(op.f('ix_student_classes_status'), table_name='student_classes')
    op.drop_index(op.f('ix_student_classes_roll_number'), table_name='student_classes')
    op.drop_index(op.f('ix_student_classes_is_active'), table_name='student_classes')
    op.drop_index(op.f('ix_student_classes_classroom_id'), table_name='student_classes')
    op.drop_index(op.f('ix_student_classes_academic_sessions_id'), table_name='student_classes')
    op.drop_index('idx_studentclass_student', table_name='student_classes')
    op.drop_index('idx_studentclass_status', table_name='student_classes')
    op.drop_index('idx_studentclass_session', table_name='student_classes')
    op.drop_index('idx_studentclass_roll', table_name='student_classes')
    op.drop_index('idx_studentclass_class', table_name='student_classes')
    op.drop_table('student_classes')
    op.drop_index(op.f('ix_notices_publish_date'), table_name='notices')
    op.drop_index(op.f('ix_notices_notice_type'), table_name='notices')
    op.drop_index(op.f('ix_notices_is_pinned'), table_name='notices')
    op.drop_index(op.f('ix_notices_is_active'), table_name='notices')
    op.drop_index(op.f('ix_notices_expiry_date'), table_name='notices')
    op.drop_index(op.f('ix_notices_classroom_id'), table_name='notices')
    op.drop_index(op.f('ix_notices_audience'), table_name='notices')
    op.drop_index(op.f('ix_notices_academic_sessions_id'), table_name='notices')
    op.drop_index('idx_notice_publish', table_name='notices')
    op.drop_index('idx_notice_pin', table_name='notices')
    op.drop_index('idx_notice_class', table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_class_subjects_subject_id'), table_name='class_subjects')
    op.drop_index(op.f('ix_class_subjects_is_active'), table_name='class_subjects')
    op.drop_index(op.f('ix_class_subjects_classroom_id'), table_name='class_subjects')
    op.drop_index(op.f('ix_class_subjects_academic_sessions_id'), table_name='class_subjects')
    op.drop_index('idx_class_subject_subject', table_name='class_subjects')
    op.drop_index('idx_class_subject_session', table_name='class_subjects')
    op.drop_index('idx_class_subject_class', table_name='class_subjects')
    op.drop_index('idx_class_subject_active', table_name='class_subjects')
    op.drop_table('class_subjects')
    op.drop_index(op.f('ix_zoom_transcript_zoom_file_id'), table_name='zoom_transcript')
    op.drop_index(op.f('ix_zoom_transcript_speaker'), table_name='zoom_transcript')
    op.drop_index(op.f('ix_zoom_transcript_class_date'), table_name='zoom_transcript')
    op.drop_index('idx_zoom_transcript_speaker', table_name='zoom_transcript')
    op.drop_index('idx_zoom_transcript_file', table_name='zoom_transcript')
    op.drop_index('idx_zoom_transcript_class_date', table_name='zoom_transcript')
    op.drop_table('zoom_transcript')
    op.drop_index(op.f('ix_zoom_student_interaction_zoom_file_id'), table_name='zoom_student_interaction')
    op.drop_index(op.f('ix_zoom_student_interaction_speaker_name'), table_name='zoom_student_interaction')
    op.drop_index(op.f('ix_zoom_student_interaction_class_date'), table_name='zoom_student_interaction')
    op.drop_index('idx_zoom_interaction_speaker', table_name='zoom_student_interaction')
    op.drop_index('idx_zoom_interaction_file', table_name='zoom_student_interaction')
    op.drop_index('idx_zoom_interaction_class_date', table_name='zoom_student_interaction')
    op.drop_table('zoom_student_interaction')
    op.drop_index(op.f('ix_student_id_cards_student_id'), table_name='student_id_cards')
    op.drop_index(op.f('ix_student_id_cards_is_active'), table_name='student_id_cards')
    op.drop_index(op.f('ix_student_id_cards_academic_sessions_id'), table_name='student_id_cards')
    op.drop_index('idx_student_id_cards_student', table_name='student_id_cards')
    op.drop_index('idx_student_id_cards_session', table_name='student_id_cards')
    op.drop_table('student_id_cards')
    op.drop_index(op.f('ix_ka_topic_progress_topic_id'), table_name='ka_topic_progress')
    op.drop_index(op.f('ix_ka_topic_progress_student_id'), table_name='ka_topic_progress')
    op.drop_index(op.f('ix_ka_topic_progress_date'), table_name='ka_topic_progress')
    op.drop_index(op.f('ix_ka_topic_progress_course_id'), table_name='ka_topic_progress')
    op.drop_index('idx_topic_progress_topic', table_name='ka_topic_progress')
    op.drop_index('idx_topic_progress_student', table_name='ka_topic_progress')
    op.drop_index('idx_topic_progress_date', table_name='ka_topic_progress')
    op.drop_table('ka_topic_progress')
    op.drop_index(op.f('ix_classroom_is_active'), table_name='classroom')
    op.drop_index(op.f('ix_classroom_class_teacher_id'), table_name='classroom')
    op.drop_index(op.f('ix_classroom_academic_sessions_id'), table_name='classroom')
    op.drop_index('idx_classroom_teacher', table_name='classroom')
    op.drop_index('idx_classroom_session', table_name='classroom')
    op.drop_index('idx_classroom_section', table_name='classroom')
    op.drop_index('idx_classroom_name', table_name='classroom')
    op.drop_index('idx_classroom_code', table_name='classroom')
    op.drop_index('idx_classroom_active', table_name='classroom')
    op.drop_table('classroom')
    op.drop_index(op.f('ix_zoom_recording_file_status'), table_name='zoom_recording_file')
    op.drop_index(op.f('ix_zoom_recording_file_meeting_uuid'), table_name='zoom_recording_file')
    op.drop_index('idx_zoom_recording_status', table_name='zoom_recording_file')
    op.drop_index('idx_zoom_recording_meeting', table_name='zoom_recording_file')
    op.drop_table('zoom_recording_file')
    op.drop_index(op.f('ix_zoom_interaction_report_report_id'), table_name='zoom_interaction_report')
    op.drop_index('idx_zoom_interaction_report', table_name='zoom_interaction_report')
    op.drop_table('zoom_interaction_report')
    op.drop_index(op.f('ix_zoom_duration_report_report_id'), table_name='zoom_duration_report')
    op.drop_index('idx_zoom_duration_report', table_name='zoom_duration_report')
    op.drop_table('zoom_duration_report')
    op.drop_index(op.f('ix_teacher_profiles_user_id'), table_name='teacher_profiles')
    op.drop_index(op.f('ix_teacher_profiles_is_active'), table_name='teacher_profiles')
    op.drop_index(op.f('ix_teacher_profiles_employee_code'), table_name='teacher_profiles')
    op.drop_index('idx_teacher_employee', table_name='teacher_profiles')
    op.drop_index('idx_teacher_department', table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index(op.f('ix_subjects_subject_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_is_active'), table_name='subjects')
    op.drop_index('idx_subject_name', table_name='subjects')
    op.drop_index('idx_subject_active', table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_registration_number'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_is_active'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_admission_number'), table_name='student_profiles')
    op.drop_index('idx_student_id', table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_ka_topic_topic_name'), table_name='ka_topic')
    op.drop_index(op.f('ix_ka_topic_topic_id'), table_name='ka_topic')
    op.drop_index(op.f('ix_ka_topic_course_id'), table_name='ka_topic')
    op.drop_index('idx_ka_topic_name', table_name='ka_topic')
    op.drop_index('idx_ka_topic_course', table_name='ka_topic')
    op.drop_table('ka_topic')
    op.drop_index(op.f('ix_admin_profiles_user_id'), table_name='admin_profiles')
    op.drop_index(op.f('ix_admin_profiles_is_active'), table_name='admin_profiles')
    op.drop_index(op.f('ix_admin_profiles_admin_id'), table_name='admin_profiles')
    op.drop_index('idx_admin_id', table_name='admin_profiles')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_zoom_meeting_start_time'), table_name='zoom_meeting')
    op.drop_index(op.f('ix_zoom_meeting_meeting_id'), table_name='zoom_meeting')
    op.drop_index(op.f('ix_zoom_meeting_host_id'), table_name='zoom_meeting')
    op.drop_index('idx_zoom_meeting_start_time', table_name='zoom_meeting')
    op.drop_index('idx_zoom_meeting_meeting_id', table_name='zoom_meeting')
    op.drop_index('idx_zoom_meeting_host', table_name='zoom_meeting')
    op.drop_table('zoom_meeting')
    op.drop_index(op.f('ix_zoom_file_file_initial'), table_name='zoom_file')
    op.drop_index(op.f('ix_zoom_file_date'), table_name='zoom_file')
    op.drop_index('idx_zoom_file_date', table_name='zoom_file')
    op.drop_table('zoom_file')
    op.drop_index(op.f('ix_week_days_is_active'), table_name='week_days')
    op.drop_index('idx_weekday_order', table_name='week_days')
    op.drop_index('idx_weekday_name', table_name='week_days')
    op.drop_index('idx_weekday_code', table_name='week_days')
    op.drop_table('week_days')
    op.drop_index(op.f('ix_users_teacher_id'), table_name='users')
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_admin_id'), table_name='users')
    op.drop_index('idx_user_role_active', table_name='users')
    op.drop_index('idx_user_phone_active', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_time_slots_is_active'), table_name='time_slots')
    op.drop_index('idx_slot_order', table_name='time_slots')
    op.drop_index('idx_slot_code', table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_table('student_report')
    op.drop_table('ka_student')
    op.drop_table('ka_course')
    op.drop_index(op.f('ix_attachments_is_active'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_academic_sessions_is_current'), table_name='academic_sessions')
    op.drop_index(op.f('ix_academic_sessions_is_active'), table_name='academic_sessions')
    op.drop_index('idx_session_name', table_name='academic_sessions')
    op.drop_index('idx_session_active', table_name='academic_sessions')
    op.drop_table('academic_sessions')
    # ### end Alembic commands ###
